apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: crs-cloud-credentials-imds
  labels:
    generated-by: qualys-crs
    qualys.com/rule-id: Cloud_Credentials_accessed_by_network_utility_T1552_005
    mitre.attack/technique: T1552.005
    mitre.attack/tactic: credential-access
    policy.qualys.com/severity: critical
  annotations:
    description: Detect network utilities accessing cloud instance metadata
spec:
  kprobes:
  - call: sys_connect
    syscall: true
    args:
    - index: 1
      type: sockaddr
    selectors:
    - matchArgs:
      - index: 1
        operator: SAddr
        values:
        - 169.254.169.254
      matchBinaries:
      - operator: In
        values:
        - /usr/bin/curl
        - /usr/bin/wget
        - /usr/bin/fetch
      matchActions:
      - action: Post
