apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: crs-cryptominer-execution
  labels:
    generated-by: qualys-crs
    qualys.com/rule-id: CryptoMiner_Execution_T1496
    mitre.attack/technique: T1496
    mitre.attack/tactic: impact
    policy.qualys.com/severity: critical
  annotations:
    description: Detect crypto miner process execution
spec:
  kprobes:
  - call: sys_execve
    syscall: true
    args:
    - index: 0
      type: string
    selectors:
    - matchArgs:
      - index: 0
        operator: Postfix
        values:
        - /xmrig
        - /minerd
        - /cpuminer
        - /cgminer
        - /bfgminer
        - /ethminer
        - /nbminer
        - /t-rex
        - /gminer
        - /phoenixminer
      matchActions:
      - action: Post
  - call: sys_connect
    syscall: true
    args:
    - index: 1
      type: sockaddr
    selectors:
    - matchArgs:
      - index: 1
        operator: DPort
        values:
        - '3333'
        - '4444'
        - '5555'
        - '7777'
        - '8888'
        - '9999'
        - '14433'
        - '14444'
        - '45700'
      matchActions:
      - action: Post
