apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: crs-db-program-spawned
  labels:
    generated-by: qualys-crs
    qualys.com/rule-id: DB_program_spawned_process_T1210
    mitre.attack/technique: T1210
    mitre.attack/tactic: lateral-movement
    policy.qualys.com/severity: critical
  annotations:
    description: Detect database program spawning shell
spec:
  kprobes:
  - call: sys_execve
    syscall: true
    args:
    - index: 0
      type: string
    selectors:
    - matchArgs:
      - index: 0
        operator: Postfix
        values:
        - /sh
        - /bash
      matchBinaries:
      - operator: In
        values:
        - /usr/bin/mysql
        - /usr/bin/psql
        - /usr/bin/mongo
        - /usr/bin/redis-cli
        - /usr/bin/sqlite3
      matchActions:
      - action: Post
