apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: crs-netcat-reverse-shell
  labels:
    generated-by: qualys-crs
    qualys.com/rule-id: Netcat_Reverse_Shell_Execution_T1059_004
    mitre.attack/technique: T1059.004
    mitre.attack/tactic: execution
    policy.qualys.com/severity: critical
  annotations:
    description: Detect netcat reverse shell execution
spec:
  kprobes:
  - call: sys_execve
    syscall: true
    args:
    - index: 0
      type: string
    - index: 1
      type: string
    selectors:
    - matchArgs:
      - index: 0
        operator: Postfix
        values:
        - /nc
        - /netcat
        - /ncat
      - index: 1
        operator: Contains
        values:
        - -e
        - -c
      matchActions:
      - action: Post
