apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: crs-block-cap-chown-fowner-privesc
  labels:
    generated-by: qualys-crs
    qualys.com/rule-id: Privilege_Escalation_via_CAP_CHOWN_CAP_FOWNER_Capabilities_T1068
    mitre.attack/technique: T1068
    mitre.attack/tactic: privilege-escalation
    policy.qualys.com/severity: critical
    policy.qualys.com/action: block
  annotations:
    description: Detect privilege escalation via CAP_CHOWN or CAP_FOWNER capabilities
spec:
  kprobes:
  - call: sys_execve
    syscall: true
    args:
    - index: 0
      type: string
    selectors:
    - matchCapabilities:
      - type: Effective
        operator: In
        values:
        - CAP_CHOWN
        - CAP_FOWNER
      matchActions:
      - action: Sigkill
  - call: sys_chown
    syscall: true
    args:
    - index: 0
      type: string
    - index: 1
      type: int
    - index: 2
      type: int
    selectors:
    - matchArgs:
      - index: 0
        operator: Prefix
        values:
        - /etc/passwd
        - /etc/shadow
        - /etc/sudoers
      matchActions:
      - action: Sigkill
