apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: crs-block-curl-socks-proxy
  labels:
    generated-by: qualys-crs
    qualys.com/rule-id: Curl_Using_Socks_Proxy_T1572
    mitre.attack/technique: T1572
    mitre.attack/tactic: command-and-control
    policy.qualys.com/severity: high
    policy.qualys.com/action: block
  annotations:
    description: Detect curl using SOCKS proxy for tunneling
spec:
  kprobes:
  - call: sys_execve
    syscall: true
    args:
    - index: 0
      type: string
    - index: 1
      type: string
    selectors:
    - matchArgs:
      - index: 0
        operator: Postfix
        values:
        - /curl
      - index: 1
        operator: Contains
        values:
        - --socks
        - -x socks
      matchActions:
      - action: Sigkill
