apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: crs-block-exploit-vsftpd
  labels:
    generated-by: qualys-crs
    qualys.com/rule-id: Exploit_vsftpd_T1190
    mitre.attack/technique: T1190
    mitre.attack/tactic: initial-access
    policy.qualys.com/severity: critical
    policy.qualys.com/action: block
  annotations:
    description: Detects exploitation of vsftpd vulnerability (CVE-2011-2523)
spec:
  kprobes:
  - call: sys_execve
    syscall: true
    args:
    - index: 0
      type: string
    - index: 1
      type: string
    selectors:
    - matchArgs:
      - index: 0
        operator: Postfix
        values:
        - /sh
        - /bash
      matchBinaries:
      - operator: In
        values:
        - /vsftpd
        - /usr/sbin/vsftpd
      matchActions:
      - action: Sigkill
