apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: crs-block-find-aws-credentials
  labels:
    generated-by: qualys-crs
    qualys.com/rule-id: Find_AWS_Credentials_T1552_001
    mitre.attack/technique: T1552.001
    mitre.attack/tactic: credential-access
    policy.qualys.com/severity: high
    policy.qualys.com/action: block
  annotations:
    description: Detect searching for AWS credential files
spec:
  kprobes:
  - call: sys_openat
    syscall: true
    args:
    - index: 1
      type: string
    selectors:
    - matchArgs:
      - index: 1
        operator: Postfix
        values:
        - /.aws/credentials
        - /.aws/config
        - /credentials.json
      matchActions:
      - action: Sigkill
