apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: crs-block-network-scanning
  labels:
    generated-by: qualys-crs
    qualys.com/rule-id: Network_scanning_utility_T1046
    mitre.attack/technique: T1046
    mitre.attack/tactic: discovery
    policy.qualys.com/severity: high
    policy.qualys.com/action: block
  annotations:
    description: Detect network scanning utility execution
spec:
  kprobes:
  - call: sys_execve
    syscall: true
    args:
    - index: 0
      type: string
    selectors:
    - matchArgs:
      - index: 0
        operator: Postfix
        values:
        - /nmap
        - /masscan
        - /zmap
        - /rustscan
        - /unicornscan
      matchActions:
      - action: Sigkill
  - call: sys_socket
    syscall: true
    args:
    - index: 1
      type: int
    selectors:
    - matchArgs:
      - index: 1
        operator: Equal
        values:
        - '3'
      matchActions:
      - action: Sigkill
