apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: credential-access-detection
  labels:
    app.kubernetes.io/name: qualys-threat-detection
    threat.qualys.com/category: credential-access
    mitre.attack/tactic: credential-access
    mitre.attack/technique: T1552
spec:
  kprobes:
  # Monitor access to sensitive credential files
  - call: "sys_openat"
    syscall: true
    args:
    - index: 1
      type: "string"
    selectors:
    # Linux credential files
    - matchArgs:
      - index: 1
        operator: "Equal"
        values:
        - "/etc/passwd"
        - "/etc/shadow"
        - "/etc/gshadow"
        - "/etc/sudoers"
        - "/etc/security/opasswd"
      matchActions:
      - action: Post
    # SSH keys
    - matchArgs:
      - index: 1
        operator: "Postfix"
        values:
        - "/.ssh/id_rsa"
        - "/.ssh/id_dsa"
        - "/.ssh/id_ecdsa"
        - "/.ssh/id_ed25519"
        - "/.ssh/authorized_keys"
        - "/.ssh/known_hosts"
      matchActions:
      - action: Post
    # Cloud credentials
    - matchArgs:
      - index: 1
        operator: "Postfix"
        values:
        - "/.aws/credentials"
        - "/.aws/config"
        - "/.azure/credentials"
        - "/.config/gcloud/credentials.db"
        - "/.kube/config"
      matchActions:
      - action: Post
    # Application secrets
    - matchArgs:
      - index: 1
        operator: "Postfix"
        values:
        - ".env"
        - ".env.local"
        - ".env.production"
        - "config.json"
        - "secrets.yaml"
        - "secrets.json"
        - "credentials.json"
      matchActions:
      - action: Post
        rateLimit: "1m"

  # Monitor environment variable access (for secrets)
  - call: "sys_execve"
    syscall: true
    args:
    - index: 0
      type: "string"
    selectors:
    - matchArgs:
      - index: 0
        operator: "Postfix"
        values:
        - "/env"
        - "/printenv"
      matchActions:
      - action: Post

  # Detect credential dumping tools
  - call: "sys_execve"
    syscall: true
    args:
    - index: 0
      type: "string"
    selectors:
    - matchArgs:
      - index: 0
        operator: "Postfix"
        values:
        - "/mimikatz"
        - "/lazagne"
        - "/truffleHog"
        - "/gitleaks"
        - "/unshadow"
        - "/john"
        - "/hashcat"
      matchActions:
      - action: Post
