# Credential Access Detection
# Maturity: stable
# Priority: HIGH
# Reference: Falco "Read sensitive file trusted after startup"
# MITRE ATT&CK: T1552 - Unsecured Credentials
---
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: cred-access-shadow-file
  labels:
    policy.qualys.com/maturity: stable
    policy.qualys.com/priority: high
    policy.qualys.com/category: file
    mitre.attack/tactic: credential-access
    mitre.attack/technique: T1552.001
    qualys.com/severity: "4"
  annotations:
    description: |
      Detects access to /etc/shadow and other sensitive credential files.
      Access to these files outside of authentication contexts is suspicious.
    falco-equivalent: "Read sensitive file trusted after startup"
spec:
  kprobes:
  - call: "sys_openat"
    syscall: true
    args:
    - index: 1
      type: "string"
    selectors:
    - matchArgs:
      - index: 1
        operator: "Equal"
        values:
        - "/etc/shadow"
        - "/etc/gshadow"
        - "/etc/master.passwd"
        - "/etc/security/opasswd"
      matchActions:
      - action: Post
---
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: cred-access-ssh-keys
  labels:
    policy.qualys.com/maturity: stable
    policy.qualys.com/priority: high
    policy.qualys.com/category: file
    mitre.attack/tactic: credential-access
    mitre.attack/technique: T1552.004
    qualys.com/severity: "4"
  annotations:
    description: |
      Detects access to SSH private keys. Unauthorized access to these
      files could lead to lateral movement.
spec:
  kprobes:
  - call: "sys_openat"
    syscall: true
    args:
    - index: 1
      type: "string"
    selectors:
    - matchArgs:
      - index: 1
        operator: "Postfix"
        values:
        - "/.ssh/id_rsa"
        - "/.ssh/id_dsa"
        - "/.ssh/id_ecdsa"
        - "/.ssh/id_ed25519"
        - "/.ssh/identity"
      matchActions:
      - action: Post
---
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: cred-access-cloud-credentials
  labels:
    policy.qualys.com/maturity: stable
    policy.qualys.com/priority: high
    policy.qualys.com/category: file
    mitre.attack/tactic: credential-access
    mitre.attack/technique: T1552.001
    qualys.com/severity: "4"
  annotations:
    description: |
      Detects access to cloud provider credential files (AWS, GCP, Azure).
      These files contain sensitive access keys.
spec:
  kprobes:
  - call: "sys_openat"
    syscall: true
    args:
    - index: 1
      type: "string"
    selectors:
    - matchArgs:
      - index: 1
        operator: "Postfix"
        values:
        - "/.aws/credentials"
        - "/.aws/config"
        - "/.azure/credentials"
        - "/.config/gcloud/credentials.db"
        - "/.config/gcloud/access_tokens.db"
        - "/.config/gcloud/application_default_credentials.json"
        - "/.kube/config"
      matchActions:
      - action: Post
---
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: cred-access-k8s-secrets
  labels:
    policy.qualys.com/maturity: stable
    policy.qualys.com/priority: high
    policy.qualys.com/category: file
    mitre.attack/tactic: credential-access
    mitre.attack/technique: T1552.007
    qualys.com/severity: "4"
  annotations:
    description: |
      Monitors access to Kubernetes service account tokens.
      These tokens can be used for lateral movement within the cluster.
spec:
  kprobes:
  - call: "sys_openat"
    syscall: true
    args:
    - index: 1
      type: "string"
    selectors:
    - matchArgs:
      - index: 1
        operator: "Prefix"
        values:
        - "/var/run/secrets/kubernetes.io"
        - "/run/secrets/kubernetes.io"
      matchActions:
      - action: Post
        rateLimit: "1m"
