# Cryptominer Detection and Prevention
# Maturity: stable
# Priority: HIGH
# Reference: Falco "Detect crypto miners using the Stratum protocol"
# MITRE ATT&CK: T1496 - Resource Hijacking
---
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: cryptominer-binary-block
  labels:
    policy.qualys.com/maturity: stable
    policy.qualys.com/priority: high
    policy.qualys.com/category: process
    mitre.attack/tactic: impact
    mitre.attack/technique: T1496
    qualys.com/severity: "4"
  annotations:
    description: |
      Blocks execution of known cryptocurrency mining binaries.
      High confidence detection with minimal false positives.
    falco-equivalent: "Detect crypto miners using the Stratum protocol"
spec:
  kprobes:
  - call: "sys_execve"
    syscall: true
    args:
    - index: 0
      type: "string"
    selectors:
    - matchArgs:
      - index: 0
        operator: "Postfix"
        values:
        # XMRig and variants
        - "xmrig"
        - "xmr-stak"
        - "xmr-stak-cpu"
        - "xmr-stak-amd"
        - "xmr-stak-nvidia"
        # CPU miners
        - "minerd"
        - "cpuminer"
        - "cpuminer-multi"
        # GPU miners
        - "cgminer"
        - "bfgminer"
        - "ethminer"
        - "ccminer"
        - "nheqminer"
        # Other common miners
        - "cryptonight"
        - "minergate"
        - "nicehash"
        - "claymore"
        - "phoenixminer"
        - "t-rex"
        - "nbminer"
        - "gminer"
        - "lolminer"
        # Common disguises
        - "kswapd0"
        - "watchdogs"
        - "kdevtmpfsi"
        - "kinsing"
      matchActions:
      - action: Sigkill
---
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: cryptominer-pool-connection-block
  labels:
    policy.qualys.com/maturity: stable
    policy.qualys.com/priority: high
    policy.qualys.com/category: network
    mitre.attack/tactic: impact
    mitre.attack/technique: T1496
    qualys.com/severity: "4"
  annotations:
    description: |
      Blocks connections to known cryptocurrency mining pool ports.
      Stratum protocol typically uses ports 3333, 4444, 5555.
spec:
  kprobes:
  - call: "sys_connect"
    syscall: true
    args:
    - index: 1
      type: "sockaddr"
    selectors:
    - matchArgs:
      - index: 1
        operator: "DPort"
        values:
        # Stratum protocol ports
        - "3333"
        - "4444"
        - "5555"
        - "7777"
        - "8888"
        - "9999"
        # SSL/TLS Stratum
        - "14433"
        - "14444"
        # Monero specific
        - "45700"
        - "45560"
        # Other mining ports
        - "10128"
        - "20580"
        - "13531"
      matchActions:
      - action: Sigkill
