apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: block-reverse-shell-connections
  labels:
    app.kubernetes.io/name: qualys-network-security
    threat.qualys.com/category: execution
    mitre.attack/tactic: execution
    mitre.attack/technique: T1059
spec:
  kprobes:
  # Detect and block shells making outbound connections
  - call: "sys_connect"
    syscall: true
    args:
    - index: 0
      type: "int"
    - index: 1
      type: "sockaddr"
    selectors:
    # Block shells connecting to any external IP
    - matchBinaries:
        operator: In
        values:
        - "/bin/sh"
        - "/bin/bash"
        - "/bin/dash"
        - "/bin/zsh"
        - "/bin/ash"
        - "/usr/bin/sh"
        - "/usr/bin/bash"
        - "/usr/bin/zsh"
      matchActions:
      - action: Sigkill

  # Block netcat/socat making connections
  - call: "sys_connect"
    syscall: true
    args:
    - index: 1
      type: "sockaddr"
    selectors:
    - matchBinaries:
        operator: In
        values:
        - "/bin/nc"
        - "/bin/ncat"
        - "/bin/netcat"
        - "/usr/bin/nc"
        - "/usr/bin/ncat"
        - "/usr/bin/netcat"
        - "/usr/bin/socat"
      matchActions:
      - action: Sigkill

  # Block scripting languages making raw socket connections to non-standard ports
  - call: "sys_connect"
    syscall: true
    args:
    - index: 1
      type: "sockaddr"
    selectors:
    - matchBinaries:
        operator: In
        values:
        - "/usr/bin/python"
        - "/usr/bin/python3"
        - "/usr/bin/perl"
        - "/usr/bin/ruby"
      matchArgs:
      - index: 1
        operator: "NotDPort"
        values:
        - "80"
        - "443"
        - "53"
      - index: 1
        operator: "DPortPriv"  # Connections to privileged ports (suspicious)
      matchActions:
      - action: Sigkill
